spring:
  datasource:
    url: jdbc:yugabytedb://localhost:5433/ehrbase
    driver-class-name: com.yugabyte.Driver
    hikari:
      connectionTimeout: 600000
      maximum-pool-size: 40
      connection-init-sql: 'SET yb_disable_transactional_writes=true;SET yb_enable_upsert_mode=true;'
    hikarisecond:
      maximum-pool-size: 1
  jooq:
    sql-dialect: YUGABYTEDB
