/*
 * Copyright (c) 2022 vitasystems GmbH and Hannover Medical School.
 *
 * This file is part of project EHRbase
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.webtester.service.loader.jooq;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EncodingRecord extends TableRecordImpl<EncodingRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ehr.encoding.path</code>.
     */
    public void setPath(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ehr.encoding.path</code>.
     */
    public String getPath() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ehr.encoding.code</code>.
     */
    public void setCode(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ehr.encoding.code</code>.
     */
    public Long getCode() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Encoding.ENCODING.PATH;
    }

    @Override
    public Field<Long> field2() {
        return Encoding.ENCODING.CODE;
    }

    @Override
    public String component1() {
        return getPath();
    }

    @Override
    public Long component2() {
        return getCode();
    }

    @Override
    public String value1() {
        return getPath();
    }

    @Override
    public Long value2() {
        return getCode();
    }

    @Override
    public EncodingRecord value1(String value) {
        setPath(value);
        return this;
    }

    @Override
    public EncodingRecord value2(Long value) {
        setCode(value);
        return this;
    }

    @Override
    public EncodingRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EncodingRecord
     */
    public EncodingRecord() {
        super(Encoding.ENCODING);
    }

    /**
     * Create a detached, initialised EncodingRecord
     */
    public EncodingRecord(String path, Long code) {
        super(Encoding.ENCODING);

        setPath(path);
        setCode(code);
    }
}
