/*
 * Copyright (c) 2022 vitasystems GmbH and Hannover Medical School.
 *
 * This file is part of project EHRbase
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.webtester.service.loader.jooq;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import java.util.UUID;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LoaderStateRecord extends UpdatableRecordImpl<LoaderStateRecord>
        implements Record3<UUID, String, String> {

    private static final long serialVersionUID = 1L;

    public void setId(UUID value) {
        set(0, value);
    }

    public UUID getId() {
        return (UUID) get(0);
    }

   public void setKey(String value) {
        set(1, value);
    }

    public String getKey() {
        return (String) get(1);
    }

    public void setValue(String value) {
        set(2, value);
    }

    public String getValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return LoaderState.LOADER_STATE.ID;
    }

    @Override
    public Field<String> field2() {
        return LoaderState.LOADER_STATE.KEY;
    }

    @Override
    public Field<String> field3() {
        return LoaderState.LOADER_STATE.VALUE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public LoaderStateRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public LoaderStateRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public LoaderStateRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public LoaderStateRecord values(
            UUID value1,
            String value2,
            String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoaderStateRecord
     */
    public LoaderStateRecord() {
        super(LoaderState.LOADER_STATE);
    }

    /**
     * Create a detached, initialised LoaderStateRecord
     */
    public LoaderStateRecord(
            UUID id,
            String key,
            String value) {
        super(LoaderState.LOADER_STATE);

        setId(id);
        setKey(key);
        setValue(value);;
    }
}
